#! /bin/bash
#
# run shell for bitcoind
#
# @copyright bitmain.com
# @author zhibiao.pan@bitmain.com
# 
export LC_ALL=C
SROOT=$(cd $(dirname "$0"); pwd)
cd $SROOT

BLOCK_DIR="/root/supervise_bitcoind/bitcoind_latest_block"
mkdir -p $BLOCK_DIR
bitcoind -datadir="/root/.bitcoin" -conf="/root/.bitcoin/bitcoin.conf" -blocknotify="$BLOCK_DIR"
