#! /bin/bash
#
# run shell for bitcoind
#
# @copyright bitmain.com
# @author zhibiao.pan@bitmain.com
# 
export LC_ALL=C
SROOT=$(cd $(dirname "$0"); pwd)
cd $SROOT

bitcoind -datadir="/root/.bitcoin" -conf="/root/.bitcoin/bitcoin.conf" -customlogdir=/root/.bitcoin/customlog
