---

-   name: install deps
    apt:
        name: "{{ item }}"
        update_cache: yes
        cache_valid_time: 604800
    with_items:
        - php5-mysqlnd
        - php5-curl
        - php5-cli
    tags: install

-   name: ensure dir
    file:
        path: /work/Explorer/{{ daoru_name }}
        state: directory
    tags: sync

-   name: rsync source code
    synchronize:
        src: ../../../../daoru/
        dest: /work/Explorer/{{ daoru_name }}
    notify:
        - Restart supervised process
    tags: sync

-   name: copy env files
    copy:
        src: "{{ daoru_envfile }}"
        dest: /work/Explorer/{{ daoru_name }}/.env
    notify:
        - Restart supervised process
    tags: sync

-   name: copy supervisord files
    template:
        src: supervisor.conf
        dest: /etc/supervisor/conf.d/{{ daoru_name }}.conf
    notify:
        - Restart supervised process
    tags: sync
